[package]
authors = ['Thunderous Network <https://github.com/thunder-university>']
description = 'Thunderous Network pallet for general logic.'
edition = '2018'
homepage = 'https://thunderous.network'
license = 'Unlicense'
name = 'pallet-core'
repository = 'https://github.com/thunder-university'
version = '2.0.0-rc6'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '1.3.4'

[dependencies.frame-support]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
tag = 'v2.0.0-rc6'
version = '2.0.0-rc6'

[dependencies.frame-system]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
tag = 'v2.0.0-rc6'
version = '2.0.0-rc6'

[dependencies.sp-core]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
tag = 'v2.0.0-rc6'
version = '2.0.0-rc6'

[dev-dependencies.sp-io]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
tag = 'v2.0.0-rc6'
version = '2.0.0-rc6'

[dependencies.sp-runtime]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
tag = 'v2.0.0-rc6'
version = '2.0.0-rc6'

[dependencies.primitives]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-primitives'
rev = 'acf86cd4b0ad4c45dbba57c2ae323531d5b71264'

[dev-dependencies]
pallet-randomness-collective-flip = { version = '2.0.0-rc6', default-features = false }
pallet-timestamp = { version = '2.0.0-rc6', default-features = false }

[dependencies]
sp-std = { version = '2.0.0-rc6', default-features = false }

[dependencies.unique-asset]
default-features = false
package = 'pallet-certificate'
path = '../certificate'
version = '2.0.0-rc6'

[features]
default = ['std']
std = [
    'codec/std',
    'frame-support/std',
    'frame-system/std',
    'sp-runtime/std',
    'sp-core/std',
    'primitives/std',
    'unique-asset/std',
]
