[profile.release]
panic = 'unwind'

[workspace]
members = [
    'node',
    # 'pallets/country',
    # 'pallets/block',
    'runtime',
]
exclude = [
    'luckydraw',
    'airdrop',
    'countrytoken'
]
